[CmdletBinding()]
param([ValidateSet("All","SkillsOnly","GlobalOnly","ReviewAgentsOnly")][string]$Component="All",[switch]$ForceReplaceGlobal,[switch]$NoBackup)
$ErrorActionPreference="Stop"
$ScriptDir=Split-Path -Parent $MyInvocation.MyCommand.Path;$PackageRoot=Split-Path -Parent $ScriptDir
$SourceGlobal=Join-Path $PackageRoot "global\AGENTS.md";$SourceSkills=Join-Path $PackageRoot "skills";$SourceAgents=Join-Path $PackageRoot "custom-agents"
$CodexHome=if($env:CODEX_HOME){$env:CODEX_HOME}else{Join-Path $HOME ".codex"};$SkillsHome=Join-Path (Join-Path $HOME ".agents") "skills";$AgentsHome=Join-Path $CodexHome "agents"
$Timestamp=Get-Date -Format "yyyyMMdd-HHmmss";$BackupRoot=Join-Path (Join-Path $HOME ".codex-skill-backups") $Timestamp
$BeginMarker="<!-- codex-cross-project-assistant:begin -->";$EndMarker="<!-- codex-cross-project-assistant:end -->";$DeprecatedSkills=@("vue-frontend-engineering")
function Backup-Path{param([string]$Path,[string]$RelativeName);if($NoBackup -or -not(Test-Path -LiteralPath $Path)){return};$D=Join-Path $BackupRoot $RelativeName;New-Item -ItemType Directory -Force -Path (Split-Path -Parent $D)|Out-Null;Copy-Item -LiteralPath $Path -Destination $D -Recurse -Force;Write-Host "已备份: $Path -> $D"}
function Install-Global{if(-not(Test-Path $SourceGlobal)){throw "缺少全局规则"};$M=Get-Content $SourceGlobal -Raw -Encoding UTF8;New-Item -ItemType Directory -Force -Path $CodexHome|Out-Null;$T=Join-Path $CodexHome "AGENTS.md";Backup-Path $T "codex\AGENTS.md";if($ForceReplaceGlobal -or -not(Test-Path $T)){Set-Content $T $M -Encoding UTF8;return};$E=Get-Content $T -Raw -Encoding UTF8;$bc=([regex]::Matches($E,[regex]::Escape($BeginMarker))).Count;$ec=([regex]::Matches($E,[regex]::Escape($EndMarker))).Count;if($bc-ne$ec -or $bc-gt1){throw "AGENTS.md 受管标记异常"};if($bc-eq0){$R=$E.TrimEnd()+"`r`n`r`n"+$M.Trim()+"`r`n"}else{$P="(?s)"+[regex]::Escape($BeginMarker)+".*?"+[regex]::Escape($EndMarker);$R=[regex]::Replace($E,$P,$M.Trim(),1)};Set-Content $T $R -Encoding UTF8}
function Remove-DeprecatedSkills{foreach($N in $DeprecatedSkills){$T=Join-Path $SkillsHome $N;if(Test-Path $T){Backup-Path $T (Join-Path "deprecated-skills" $N);Remove-Item $T -Recurse -Force;Write-Host "已迁移并移除旧 Skill: $N"}}}
function Install-Skills{New-Item -ItemType Directory -Force -Path $SkillsHome|Out-Null;Remove-DeprecatedSkills;Get-ChildItem $SourceSkills -Directory|Sort-Object Name|ForEach-Object{$T=Join-Path $SkillsHome $_.Name;Backup-Path $T (Join-Path "skills" $_.Name);if(Test-Path $T){Remove-Item $T -Recurse -Force};Copy-Item $_.FullName $T -Recurse -Force;Write-Host "已安装 Skill: $($_.Name)"}}
function Install-ReviewAgents{New-Item -ItemType Directory -Force -Path $AgentsHome|Out-Null;Get-ChildItem $SourceAgents -File -Filter "*.toml"|Sort-Object Name|ForEach-Object{$T=Join-Path $AgentsHome $_.Name;Backup-Path $T (Join-Path "agents" $_.Name);Copy-Item $_.FullName $T -Force;Write-Host "已安装 Reviewer: $($_.Name)"}}
switch($Component){"All"{Install-Global;Install-Skills;Install-ReviewAgents}"SkillsOnly"{Install-Skills}"GlobalOnly"{Install-Global}"ReviewAgentsOnly"{Install-ReviewAgents}}
Write-Host "安装完成。请重启 Codex 并运行 /skills。"
